### ISSUE TITLE
Speed Test Error: We're sorry, but something went wrong.

### ISSUE THREAD

**Issue by webaissance** [Hack4Eugene/SpeedUpAmerica#277]
**Error when running a speed test**
When running a speed test I am getting an error:

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

**To Reproduce**
1. Go to 'https://speedupamerica.com/'
2. Click on 'Take the Test!!!'
3. Take the speed test. I clicked on "Use my browser's location." ->  Location Success! -> Let's begin. -> Residential. -> Let's do this! -> connection type: wireless -> Test my Speed -> Measuring Upload and download speed -> submitting data ->
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

**Expected behavior**
Expected to see results of test

**Screenshots**
![image](https://user-images.githubusercontent.com/4278468/133306240-c8b69aeb-7f29-4714-a9e9-db0ce0b297af.png)

**Desktop (please complete the following information):**
 - OS & Version: Windows 10 Home Version 20H2
 - Browser: Chrome Version 93.0.4577.63 (Official Build) (64-bit)

Also occurs on mobile - both using Wifi and also using Cellular connection
**Smartphone **
 - Device: Samsung Galaxy S9 SM-G960U1
 - OS: Android
 - Browser Chrome 93.0 4577.62

**Additional context**
When I run the test on my local machine it gives more details about the issue:

ActiveRecord::StatementInvalid in SubmissionsController#create
Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1: UPDATE submissions SET location = POINT(longitude, latitude) WHERE id =

Extracted source (around line #675):
def populate_location
    conn = ActiveRecord::Base.connection
    conn.execute("UPDATE submissions SET location = POINT(longitude, latitude) WHERE id = #{id}")
  end

  def populate_boundaries

Rails.root: /suyc

Application Trace | Framework Trace | Full Trace
app/models/submission.rb:675:in `populate_location'
app/models/submission.rb:107:in `create_submission'
app/controllers/submissions_controller.rb:20:in `create'
Request
Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"xUZvQunSOkSnqY+9do0+5YdVSyey8MrrgAUxSfulCxmWmOGNfoCnA3t3XE1THJpsDj1e+hWtcmaa2FXh3vNC6w==",
 "submission"=>{"latitude"=>"45.5373677",
 "longitude"=>"-122.62784359999999",
 "accuracy"=>"1519",
 "actual_down_speed"=>"465.29",
 "actual_upload_speed"=>"248.47",
 "hostname"=>"ndt-iupui-mlab1-sea08.mlab-oti.measurement-lab.org",
 "address"=>"",
 "zip_code"=>"",
 "ping"=>"6.00",
 "location"=>"Location Geolocation",
 "testing_for"=>"Home Wifi",
 "connected_with"=>"Wireless connection,
 single device,
 Wireless connection,
 single device",
 "monthly_price"=>"100",
 "provider_down_speed"=>"1000",
 "rating"=>"5"},
 "start_ndt_test"=>""}

**Comment by mattsayre** [comment]
@critzo any thoughts on this bug @webaissance seeing above? I recall that sometimes certain mlab servers have trouble and this api call is hitting ndt-iupui-mlab1-sea08.mlab-oti.measurement-lab.org specifically

**Comment by critzo** [comment]
@mattsayre I ran a couple tests and am not getting the same issue. I'll see about getting a vpn'd connection to the Seattle region to re-test.

@robertodauria could you take a look?

**Comment by robertodauria** [comment]
@mattsayre There doesn't seem to be a problem with the NDT client specifically, but with how the test results are saved by the backend.

From the logs above, the data object passed to the backend was complete with download/upload speed and ping:
```
{
  "utf8": "✓",
  "authenticity_token": "xUZvQunSOkSnqY+9do0+5YdVSyey8MrrgAUxSfulCxmWmOGNfoCnA3t3XE1THJpsDj1e+hWtcmaa2FXh3vNC6w==",
  "submission": {
    "latitude": "45.5373677",
    "longitude": "-122.62784359999999",
    "accuracy": "1519",
    "actual_down_speed": "465.29",
    "actual_upload_speed": "248.47",
    "hostname": "ndt-iupui-mlab1-sea08.mlab-oti.measurement-lab.org",
    "address": "",
    "zip_code": "",
    "ping": "6.00",
    "location": "Location Geolocation",
    "testing_for": "Home Wifi",
    "connected_with": "Wireless connection,single device,Wireless connection,single device",
    "monthly_price": "100",
    "provider_down_speed": "1000",
    "rating": "5"
  },
  "start_ndt_test": ""
}

```

I ran a few tests both on the SpeedUPAmerica website and on a local instance and compared the data from my successful submissions with the above, sending the same values where possible (e.g. `monthly_price`, `provider_down_speed`, etc). 

The data passed to the /submission endpoint has the same structure, and on both https://speedupamerica.com/ and my local instance the submission worked as intended.

Looking at the backend code and the logs above, it seems the problem is happening [here](https://github.com/Hack4Eugene/SpeedUpAmerica/blob/700308f3db48cfb62e5ed1a1e38e0da2b2c4996b/app/models/submission.rb#L675), when the `location` is updated after saving the `Submission` object:
```
 conn.execute("UPDATE submissions SET location = POINT(longitude, latitude) WHERE id = #{id}")
```

that produced the following error:
```
Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1: UPDATE submissions SET location = POINT(longitude, latitude) WHERE id =
```

It seems that for some reason the Submission record that has just been created doesn't have an `id`, but I wasn't able to replicate this on my local instance in any way. I suppose that for the `id` to be empty, `save` must have failed (since it's auto-generated by MySQL), and in that case. 

(I am not an expert on Ruby/RoR by any means, so I may not be understanding the code fully. Please disregard the following if it doesn't make sense :slightly_smiling_face: )

There are some [validations](https://github.com/Hack4Eugene/SpeedUpAmerica/blob/700308f3db48cfb62e5ed1a1e38e0da2b2c4996b/app/models/submission.rb#L46) declared for the `Submission` model. All of them should be passing with the above data, except for `provider`, which is populated from MaxMind. Are all the provider names in MaxMind shorter than 255 characters?

IIUC by the documentation, [save](https://github.com/Hack4Eugene/SpeedUpAmerica/blob/700308f3db48cfb62e5ed1a1e38e0da2b2c4996b/app/models/submission.rb#L105) returns `false` if any validation fails, but that return value does not seem to be checked, so the call to `populate_location` would happen anyway (and probably fail exactly as in the output above, since the Submission hasn't been actually saved and no `id` has been generated to use in the `UPDATE`).

**Comment by webaissance** [comment]
Thank you all for your feedback.
The issue seems to be with CenturyLink Fiber. I have tested this quite a bit and every time I run the test with my CenturyLink Fiber it gives the error above - regardless of whether it's on Chrome, Firefox or on my Samsung phone, and on the live site or on the local site.
But when I use the Credo / Verizon cell data on either the phone or as a mobile hot-spot for the computer - the speed tests work. The same is true on the live site and on my local site.
I'm not sure why yet - but something about the CenturyLink Fiber isn't working.
I will keep trying to track it down based on the logs and other clues I can find.
